// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/avatars': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/avatars.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refresh.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signup.post').default>>>>
    }
    '/api/categories/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/add.post').default>>>>
    }
    '/api/categories/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/delete.delete').default>>>>
    }
    '/api/categories/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/list.get').default>>>>
    }
    '/api/db': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/db.get').default>>>>
    }
    '/api/invoices/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/add.post').default>>>>
    }
    '/api/invoices/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/delete.delete').default>>>>
    }
    '/api/invoices/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/list.get').default>>>>
    }
    '/api/invoices/pay': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/pay.patch').default>>>>
    }
    '/api/invoices/update': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/update.patch').default>>>>
    }
    '/api/tasks/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/add.post').default>>>>
    }
    '/api/tasks/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/delete.delete').default>>>>
    }
    '/api/tasks/toggle': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/toggle.patch').default>>>>
    }
    '/api/user/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/delete.delete').default>>>>
    }
    '/api/user/update': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/update.patch').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}